apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          value: booking_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 300
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: booking-db-pvc